import type { Product, Order, Category, Stats } from './types'

// Produits SEN Jus - Jus de mil naturel senegalais
export const mockProducts: Product[] = [
  // Jus 1L
  {
    id: 1,
    name: 'Jus de Mil Classique 1L',
    description: 'Notre recette traditionnelle de jus de mil, preparee selon les methodes ancestrales senegalaises. Un gout authentique et rafraichissant, ideal pour toute la famille.',
    price: 2500,
    category: 'Jus 1L',
    stock: 50,
    images: ['/images/products/mil-classique-1l.jpg'],
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 2,
    name: 'Jus de Mil au Gingembre 1L',
    description: 'Le mariage parfait entre le mil et le gingembre frais du Senegal. Une boisson energisante aux vertus digestives reconnues.',
    price: 2800,
    category: 'Jus 1L',
    stock: 35,
    images: ['/images/products/mil-gingembre-1l.jpg'],
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 3,
    name: 'Jus de Mil au Bouye 1L',
    description: 'Une combinaison unique de mil et de bouye (pain de singe), riche en vitamines et en fibres. Le gout du Senegal dans chaque gorgee.',
    price: 3000,
    category: 'Jus 1L',
    stock: 28,
    images: ['/images/products/mil-bouye-1l.jpg'],
    created_at: '2024-01-20T10:00:00Z',
  },
  {
    id: 4,
    name: 'Jus de Mil au Tamarin 1L',
    description: 'Le mil rencontre le tamarin pour une boisson acidulee et desalterante. Parfait pour les journees chaudes de Dakar.',
    price: 2800,
    category: 'Jus 1L',
    stock: 40,
    images: ['/images/products/mil-tamarin-1l.jpg'],
    created_at: '2024-01-25T10:00:00Z',
  },

  // Jus 50cl
  {
    id: 5,
    name: 'Jus de Mil Classique 50cl',
    description: 'Format pratique de notre jus de mil traditionnel. Ideal pour emporter au travail ou a l\'ecole.',
    price: 1500,
    category: 'Jus 50cl',
    stock: 80,
    images: ['/images/products/mil-classique-50cl.jpg'],
    created_at: '2024-02-01T10:00:00Z',
  },
  {
    id: 6,
    name: 'Jus de Mil au Gingembre 50cl',
    description: 'Le boost d\'energie en format nomade. Gingembre frais et mil de qualite pour vos journees actives.',
    price: 1700,
    category: 'Jus 50cl',
    stock: 65,
    images: ['/images/products/mil-gingembre-50cl.jpg'],
    created_at: '2024-02-01T10:00:00Z',
  },
  {
    id: 7,
    name: 'Jus de Mil au Ditakh 50cl',
    description: 'Le ditakh, fruit emblematique de la Casamance, marie au mil pour une saveur unique et exotique.',
    price: 1800,
    category: 'Jus 50cl',
    stock: 45,
    images: ['/images/products/mil-ditakh-50cl.jpg'],
    created_at: '2024-02-05T10:00:00Z',
  },

  // Jus 25cl
  {
    id: 8,
    name: 'Jus de Mil Classique 25cl',
    description: 'Le format ideal pour une pause rafraichissante. Pur jus de mil sans sucre ajoute.',
    price: 800,
    category: 'Jus 25cl',
    stock: 120,
    images: ['/images/products/mil-classique-25cl.jpg'],
    created_at: '2024-02-10T10:00:00Z',
  },
  {
    id: 9,
    name: 'Jus de Mil au Bissap 25cl',
    description: 'L\'alliance du mil et du bissap (hibiscus) pour une boisson coloree et vitaminee.',
    price: 900,
    category: 'Jus 25cl',
    stock: 95,
    images: ['/images/products/mil-bissap-25cl.jpg'],
    created_at: '2024-02-10T10:00:00Z',
  },
  {
    id: 10,
    name: 'Jus de Mil Cocktail Fruits 25cl',
    description: 'Mil, mangue et papaye locales reunis dans une boisson tropicale et nourrissante.',
    price: 950,
    category: 'Jus 25cl',
    stock: 70,
    images: ['/images/products/mil-cocktail-25cl.jpg'],
    created_at: '2024-02-15T10:00:00Z',
  },

  // Packs
  {
    id: 11,
    name: 'Pack Decouverte SEN Jus',
    description: 'Decouvrez nos 4 saveurs en format 50cl: Classique, Gingembre, Bouye et Tamarin. Le pack ideal pour une premiere experience SEN Jus.',
    price: 6000,
    category: 'Packs',
    sous_category: 'Decouverte',
    stock: 25,
    images: ['/images/products/pack-decouverte.jpg'],
    created_at: '2024-02-20T10:00:00Z',
  },
  {
    id: 12,
    name: 'Pack Famille 6x1L',
    description: 'Le pack economique pour toute la famille. 6 bouteilles de 1L de Jus de Mil Classique a prix reduit.',
    price: 13500,
    category: 'Packs',
    sous_category: 'Famille',
    stock: 20,
    images: ['/images/products/pack-famille.jpg'],
    created_at: '2024-02-20T10:00:00Z',
  },
  {
    id: 13,
    name: 'Pack Bureau 12x25cl',
    description: 'Parfait pour le bureau ou les evenements. 12 bouteilles de 25cl variees pour partager le gout du Senegal.',
    price: 9000,
    category: 'Packs',
    sous_category: 'Bureau',
    stock: 30,
    images: ['/images/products/pack-bureau.jpg'],
    created_at: '2024-02-25T10:00:00Z',
  },
  {
    id: 14,
    name: 'Pack Premium Gingembre',
    description: 'Pour les amateurs de gingembre: 3x1L + 6x50cl de notre Jus de Mil au Gingembre. Energie et vitalite garanties.',
    price: 18000,
    category: 'Packs',
    sous_category: 'Premium',
    stock: 15,
    images: ['/images/products/pack-gingembre.jpg'],
    created_at: '2024-03-01T10:00:00Z',
  },
]

export const mockOrders: Order[] = [
  {
    id: 1001,
    client_name: 'Mamadou Diallo',
    client_email: 'mamadou.diallo@email.sn',
    client_phone: '+221 77 123 45 67',
    items: [
      { product_id: 1, quantity: 2, price: 2500, product_name: 'Jus de Mil Classique 1L' },
      { product_id: 5, quantity: 4, price: 1500, product_name: 'Jus de Mil Classique 50cl' },
    ],
    total: 11000,
    status: 'livree',
    address: 'Almadies, Dakar',
    created_at: '2024-03-10T14:30:00Z',
  },
  {
    id: 1002,
    client_name: 'Fatou Ndiaye',
    client_email: 'fatou.ndiaye@email.sn',
    client_phone: '+221 78 234 56 78',
    items: [
      { product_id: 11, quantity: 1, price: 6000, product_name: 'Pack Decouverte SEN Jus' },
    ],
    total: 6000,
    status: 'validee',
    address: 'Mermoz, Dakar',
    created_at: '2024-03-12T09:15:00Z',
  },
  {
    id: 1003,
    client_name: 'Ousmane Sow',
    client_email: 'ousmane.sow@email.sn',
    client_phone: '+221 76 345 67 89',
    items: [
      { product_id: 2, quantity: 3, price: 2800, product_name: 'Jus de Mil au Gingembre 1L' },
      { product_id: 6, quantity: 6, price: 1700, product_name: 'Jus de Mil au Gingembre 50cl' },
    ],
    total: 18600,
    status: 'en_cours',
    address: 'Sacre-Coeur, Dakar',
    created_at: '2024-03-14T11:45:00Z',
  },
  {
    id: 1004,
    client_name: 'Aminata Fall',
    client_email: 'aminata.fall@email.sn',
    client_phone: '+221 77 456 78 90',
    items: [
      { product_id: 12, quantity: 2, price: 13500, product_name: 'Pack Famille 6x1L' },
    ],
    total: 27000,
    status: 'en_attente',
    address: 'Point E, Dakar',
    created_at: '2024-03-15T08:00:00Z',
  },
  {
    id: 1005,
    client_name: 'Ibrahima Mbaye',
    client_email: 'ibrahima.mbaye@email.sn',
    client_phone: '+221 70 567 89 01',
    items: [
      { product_id: 8, quantity: 10, price: 800, product_name: 'Jus de Mil Classique 25cl' },
      { product_id: 9, quantity: 10, price: 900, product_name: 'Jus de Mil au Bissap 25cl' },
    ],
    total: 17000,
    status: 'en_attente',
    address: 'Plateau, Dakar',
    created_at: '2024-03-15T10:30:00Z',
  },
]

export const mockCategories: Category[] = [
  { id: 1, name: 'Jus 1L', sous_categories: ['Classique', 'Gingembre', 'Bouye', 'Tamarin'] },
  { id: 2, name: 'Jus 50cl', sous_categories: ['Classique', 'Gingembre', 'Ditakh'] },
  { id: 3, name: 'Jus 25cl', sous_categories: ['Classique', 'Bissap', 'Cocktail'] },
  { id: 4, name: 'Packs', sous_categories: ['Decouverte', 'Famille', 'Bureau', 'Premium'] },
]

export const mockStats: Stats = {
  total_products: 14,
  total_orders: 5,
  total_revenue: 79600,
  total_clients: 5,
  pending_orders: 2,
}
