import type { Product, Order, Category, Stats } from './types'

// Produits de test - Sen Jus (Jus de mil senegalais)
export const mockProducts: Product[] = [
  // --- Jus 1L ---
  {
    id: 1,
    name: 'Jus de Mil Nature 1L',
    description: 'Notre jus de mil 100% naturel, sans conservateur ni colorant. Saveur douce et authentique, riche en nutriments essentiels.',
    price: 1500,
    category: 'Jus 1L',
    stock: 48,
    images: ['/placeholder.jpg'],
    created_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 2,
    name: 'Jus de Mil Gingembre 1L',
    description: 'Alliance parfaite du mil et du gingembre frais. Tonique et revigorant, idéal pour bien démarrer la journée.',
    price: 1700,
    category: 'Jus 1L',
    stock: 35,
    images: ['/placeholder.jpg'],
    created_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 3,
    name: 'Jus de Mil Bissap 1L',
    description: 'Fusion unique du mil et de l'hibiscus (bissap). Un jus coloré aux notes florales et légèrement acidulées.',
    price: 1800,
    category: 'Jus 1L',
    stock: 22,
    images: ['/placeholder.jpg'],
    created_at: '2025-01-12T09:00:00Z',
  },
  {
    id: 4,
    name: 'Jus de Mil Vanille 1L',
    description: 'Douceur du mil sublimée par la vanille naturelle de Madagascar. Un régal pour toute la famille.',
    price: 1600,
    category: 'Jus 1L',
    stock: 5,
    images: ['/placeholder.jpg'],
    created_at: '2025-01-15T10:00:00Z',
  },

  // --- Jus 50cl ---
  {
    id: 5,
    name: 'Jus de Mil Nature 50cl',
    description: 'Format pratique pour emporter partout. Le même jus de mil naturel authentique dans un format nomade.',
    price: 800,
    category: 'Jus 50cl',
    stock: 60,
    images: ['/placeholder.jpg'],
    created_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 6,
    name: 'Jus de Mil Gingembre 50cl',
    description: 'Tonique au gingembre en format demi-litre. Parfait pour l'école, le bureau ou le sport.',
    price: 900,
    category: 'Jus 50cl',
    stock: 45,
    images: ['/placeholder.jpg'],
    created_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 7,
    name: 'Jus de Mil Menthe 50cl',
    description: 'Fraîcheur de la menthe mêlée à la richesse du mil. Désaltérant et rafraîchissant, idéal par forte chaleur.',
    price: 850,
    category: 'Jus 50cl',
    stock: 0,
    images: ['/placeholder.jpg'],
    created_at: '2025-01-18T11:00:00Z',
  },

  // --- Jus 25cl ---
  {
    id: 8,
    name: 'Jus de Mil Nature 25cl',
    description: 'Mini format pour les petites soifs. Le pur jus de mil dans la poche, sans sucre ajouté.',
    price: 450,
    category: 'Jus 25cl',
    stock: 100,
    images: ['/placeholder.jpg'],
    created_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 9,
    name: 'Jus de Mil Gingembre 25cl',
    description: 'Mini brique tonique au gingembre. Idéale pour les enfants et les collations en déplacement.',
    price: 500,
    category: 'Jus 25cl',
    stock: 80,
    images: ['/placeholder.jpg'],
    created_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 10,
    name: 'Jus de Mil Fraise 25cl',
    description: 'La gourmandise du mil alliée à la fraise. Un jus adoré des enfants, naturellement sucré.',
    price: 550,
    category: 'Jus 25cl',
    stock: 3,
    images: ['/placeholder.jpg'],
    created_at: '2025-01-20T09:30:00Z',
  },

  // --- Packs ---
  {
    id: 11,
    name: 'Pack Découverte (6 x 25cl)',
    description: '6 briques 25cl variées : 2 Nature, 2 Gingembre, 1 Fraise, 1 Menthe. Parfait pour découvrir toute notre gamme.',
    price: 2500,
    category: 'Packs',
    stock: 20,
    images: ['/placeholder.jpg'],
    created_at: '2025-01-22T10:00:00Z',
  },
  {
    id: 12,
    name: 'Pack Famille (4 x 1L)',
    description: '4 bouteilles d'1L assorties : 1 Nature, 1 Gingembre, 1 Bissap, 1 Vanille. Economique et généreux.',
    price: 5500,
    category: 'Packs',
    stock: 15,
    images: ['/placeholder.jpg'],
    created_at: '2025-01-22T10:00:00Z',
  },
]

export const mockOrders: Order[] = [
  {
    id: 1,
    client_name: 'Aminata Diallo',
    client_email: 'aminata.diallo@gmail.com',
    client_phone: '+221 77 123 45 67',
    address: 'Cite Keur Gorgui, Dakar',
    items: [
      { product_id: 1, product_name: 'Jus de Mil Nature 1L', quantity: 2, price: 1500 },
      { product_id: 11, product_name: 'Pack Découverte (6 x 25cl)', quantity: 1, price: 2500 },
    ],
    total: 5500,
    status: 'en_attente',
    payment_method: 'wave',
    created_at: '2025-03-20T10:30:00Z',
  },
  {
    id: 2,
    client_name: 'Moussa Ndiaye',
    client_email: 'moussa.ndiaye@outlook.com',
    client_phone: '+221 76 234 56 78',
    address: 'Parcelles Assainies Unite 17, Dakar',
    items: [
      { product_id: 12, product_name: 'Pack Famille (4 x 1L)', quantity: 1, price: 5500 },
    ],
    total: 5500,
    status: 'validee',
    payment_method: 'orange_money',
    created_at: '2025-03-18T14:15:00Z',
  },
  {
    id: 3,
    client_name: 'Fatou Sarr',
    client_email: 'fatou.sarr@yahoo.fr',
    client_phone: '+221 78 345 67 89',
    address: 'Plateau, Rue Victor Hugo, Dakar',
    items: [
      { product_id: 2, product_name: 'Jus de Mil Gingembre 1L', quantity: 3, price: 1700 },
      { product_id: 5, product_name: 'Jus de Mil Nature 50cl', quantity: 4, price: 800 },
    ],
    total: 8300,
    status: 'en_cours',
    payment_method: 'wave',
    created_at: '2025-03-19T09:45:00Z',
  },
  {
    id: 4,
    client_name: 'Oumar Ba',
    client_email: 'oumar.ba@gmail.com',
    client_phone: '+221 70 456 78 90',
    address: 'Medina, Avenue Blaise Diagne, Dakar',
    items: [
      { product_id: 8, product_name: 'Jus de Mil Nature 25cl', quantity: 6, price: 450 },
      { product_id: 9, product_name: 'Jus de Mil Gingembre 25cl', quantity: 6, price: 500 },
    ],
    total: 5700,
    status: 'livree',
    payment_method: 'orange_money',
    created_at: '2025-03-15T16:00:00Z',
  },
  {
    id: 5,
    client_name: 'Rokhaya Mbaye',
    client_email: 'rokhaya.mbaye@gmail.com',
    client_phone: '+221 77 567 89 01',
    address: 'Mermoz, Rue 10, Dakar',
    items: [
      { product_id: 3, product_name: 'Jus de Mil Bissap 1L', quantity: 2, price: 1800 },
    ],
    total: 3600,
    status: 'rejetee',
    payment_method: 'wave',
    created_at: '2025-03-14T11:20:00Z',
  },
  {
    id: 6,
    client_name: 'Ibrahim Sow',
    client_email: 'ibrahim.sow@hotmail.com',
    client_phone: '+221 76 678 90 12',
    address: 'Grand Yoff, Villa 45, Dakar',
    items: [
      { product_id: 4, product_name: 'Jus de Mil Vanille 1L', quantity: 2, price: 1600 },
      { product_id: 6, product_name: 'Jus de Mil Gingembre 50cl', quantity: 3, price: 900 },
    ],
    total: 5900,
    status: 'en_attente',
    payment_method: 'orange_money',
    created_at: '2025-03-21T08:00:00Z',
  },
  {
    id: 7,
    client_name: 'Mariama Diop',
    client_email: 'mariama.diop@gmail.com',
    client_phone: '+221 78 789 01 23',
    address: 'Sacre Coeur 3, Villa 12, Dakar',
    items: [
      { product_id: 12, product_name: 'Pack Famille (4 x 1L)', quantity: 2, price: 5500 },
      { product_id: 11, product_name: 'Pack Découverte (6 x 25cl)', quantity: 1, price: 2500 },
    ],
    total: 13500,
    status: 'en_attente',
    payment_method: 'wave',
    created_at: '2025-03-22T13:30:00Z',
  },
  {
    id: 8,
    client_name: 'Cheikh Gueye',
    client_email: 'cheikh.gueye@gmail.com',
    client_phone: '+221 77 890 12 34',
    address: 'Fann Residence, Dakar',
    items: [
      { product_id: 10, product_name: 'Jus de Mil Fraise 25cl', quantity: 5, price: 550 },
      { product_id: 5, product_name: 'Jus de Mil Nature 50cl', quantity: 2, price: 800 },
    ],
    total: 4350,
    status: 'validee',
    payment_method: 'orange_money',
    created_at: '2025-03-17T15:45:00Z',
  },
]

export const mockCategories: Category[] = [
  { id: 1, name: 'Jus 1L' },
  { id: 2, name: 'Jus 50cl' },
  { id: 3, name: 'Jus 25cl' },
  { id: 4, name: 'Packs' },
]

export const mockStats: Stats = {
  total_products: mockProducts.length,
  total_orders: mockOrders.length,
  total_revenue: mockOrders.reduce((sum, o) => sum + o.total, 0),
  total_clients: new Set(mockOrders.map(o => o.client_email)).size,
  pending_orders: mockOrders.filter(o => o.status === 'en_attente').length,
}
